name: Code Style

on: [push, pull_request]

jobs:
  style:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        php: ['7.1', '7.3', '8.0']
    name: "PHP CS Fixer - PHP v${{ matrix.php }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-suggest

      - name: List versions of installed depedencies
        run: composer show
      
      - name: Check code style
        run: vendor/bin/php-cs-fixer fix --dry-run --no-interaction --verbose
